### PR TITLE
Use all matching devices with wildcard

### LINKED ISSUE #60: Feature request: set brightness of all monitors
Hi,

Thanks for your work on brightnessctl.

It would be practical to be able to set the brightness level of all connected monitors.
For example `brightnessctl -c backlight s 10+` could set the brightness of all connected "backlight" devices.
I think it's not possible in the current state.

For example in my case I have:
```
$ ls /sys/class/backlight
amdgpu_bl0  ddcci9
```

What do you think?

Cheers,
Pierre

PS: I could also wrap brightnessctl with a shell script and run it several times, but ... :)

### PR DESCRIPTION
**Pull request by Hummer12007**
Closes #60

TODO: document

### CODE REVIEW

**Comment by hugochinchilla** [comment]
can we get this merged and released?

**Comment by Hummer12007** [comment]
@hugochinchilla @xdbob can you give it a quick look to check if it makes sense? I'll re-check and merge it by Thursday.

**Comment by hugochinchilla** [comment]
I haven't work with C since college but for what I have been able to understand makes sense, I'm glad to have this feature finally landing on master :)

**Comment by Hummer12007** [comment]
Seems ok from cursory testing

**Pull request merged**
