### PR TITLE
automatically install udev rules

### PR DESCRIPTION
**Pull request by christophgysin**
Also remove the suggestion to install it with setuid root.

### CODE REVIEW

**Comment by Hummer12007** [comment]
Forgot to respond, sorry. So, I'd like you to leave installing it SUID as an option (the way to enable either behavior is up to you). There are some usecases.

**Comment by christophgysin** [comment]
For people not using udev, I'd suggest to change the permissions of the backlight device on startup instead.

I'm curious, what is the use case for installing it SUID root?

**Comment by Hummer12007** [comment]
I've seen some folks in the wild running mdev (non-udev), besides it is simpler (think multi-user).

**Comment by christophgysin** [comment]
mdev also supports rules to change the relevant permissions.

If someone is neither using udev nor mdev, I'd suggest them to change ownership of the devices in a startup script, so that brightnessctl does not need to run as root.

What do you think? I could update the README accordingly.

**Pull request closed without merging**
