### PR TITLE
Return current value

### PR DESCRIPTION
**Pull request by christophgysin**
Change output when explicitly calling ''get" command to only return the value, similar to "max". This makes it possible to use this in scripts without additional output parsing.

If called with no explicit command, it still returns the same output as before.

### CODE REVIEW

**Comment by Hummer12007** [comment]
Thanks for the PR, though I have one question for you: did you try the `-m` option? I'll definitely merge your pr if it's helpful for you.

**Comment by christophgysin** [comment]
I did not see `--machine-readable`, thanks for pointing it out. I can also use that in my code, and parse its output. It's certainly better than parsing the default output.

I just thought it's inconsistent that `max` returns the plain value, whereas ´get´ returns the same output as if no operation was given.

In any case, thanks for brightnessctl!

**Comment by Hummer12007** [comment]
Hmm, OK, you're not the first one raising this concern, so your approach probably makes more sense to most. But could you please name the new operation info, and add it to help? (Essentially replace your first commit with https://github.com/Hummer12007/brightnessctl/pull/1/commits/8baefad61ff4b49aa11f23dd388fe910cceb5a6a ). And update the README, as well (to include the info/i command).

**Comment by christophgysin** [comment]
I cherry-picked the commits from #1. Let me know if something is still missing.

Thanks!

**Comment by Hummer12007** [comment]
Great, thanks!

**Pull request merged**
