### PR TITLE
Added flag to dissallow setting brightness to zero when using delta values

### PR DESCRIPTION
**Pull request by taingra**
I've been using brightnessctl with hotkeys on my laptop and was frustrated with how if I hit my brightness down key too many times down it would turn my display off. This setting allows me turn brightness as low as it will go without turning the display completely off. 

I'm kinda new to contributing to open source so let me know if there's anything I need to change or if you aren't interested in these changes.

### CODE REVIEW

**Comment by Hummer12007** [comment]
Hi, thanks for you contribution!
I would like you to implement this a bit differently, instead of adding a flag `--never-zero`, consider adding a flag named something like `--min-value`, which would specify the minimum value to set, if it is absent, then the minimum is not checked, if `--min-value` is specified, but without an argument, the minimum is set to 1, and if the user specifies `--min-value val` the minimum value is set to `val`

**Comment by taingra** [comment]
Thanks! Okay, those changes sound reasonable. I'll make the changes today or tomorrow and get back to you.

**Comment by taingra** [comment]
I've changed the flag to min-value and it now accepts an argument which will be used as the minimum brightness instead of 1. 

Any feedback is appreciated, thanks.

**Comment by Hummer12007** [comment]
Thanks! I'll take a look in a few days (I'm on vacation this weekend).

**Comment by Hummer12007** [comment]
Thank you!

**Pull request merged**
