### PR TITLE
Fix rounding errors when using percentages

### PR DESCRIPTION
**Pull request by modernrio**
Fixes issue #12

### CODE REVIEW

**Comment by Hummer12007** [comment]
Are you sure it should be `ceil`, and not round?

**Comment by modernrio** [comment]
Well, you could either do `ceil` in the `apply_value` function (like I did) or `round` the output in `print_device` to get the right result. Either way seems fine to me, it's up to you how you would like to have it.

**Comment by Hummer12007** [comment]
Well, I've rather meant round in apply_value function.

**Comment by modernrio** [comment]
The problem when rounding with `round` in `apply_value` is that when setting the brightness to (for example) 25% and having a max brightness value of 189 (like in my case), then the float percentage would be `0.25 * 189 = 47.25` which would get rounded down by `round` to 47. The problem with that is, that 47 now is when displayed by `print_device` with `47 / 189 = 0.24867725` gets rounded down (because of the integer conversion) to 24% (although 25% was specified). Does that make sense to you?

**Comment by Hummer12007** [comment]
Oh, I see. Didn't get too deep into your issue. Thanks for clarifying.

**Pull request merged**
