### PR TITLE
Add a manpage for brightnessctl(1)

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by Hummer12007** [comment]
Thanks for the contribution! Though I'd really like you to submit a _manpage_, not an input file for a ruby(!) script for this project without external deps (buildtime or runtime). `help2man` might help you get started with the boilerplate.

**Comment by nbraud** [comment]
@Hummer12007 Sure, I can easily rewrite that as a manpage directly.

BTW, thanks for crediting my Debian package in the README.  :)

**Comment by nbraud** [comment]
@Hummer12007 Done.

**Comment by Hummer12007** [comment]
Thanks once again! (Didn't know you're the one behind the Debian package)

**Comment by nbraud** [comment]
You are welcome  :)

**Comment by bpinto** [comment]
@Hummer12007 could we get a patch release with the man pages?

**Comment by Hummer12007** [comment]
Sure, I'll tag another version.

**Comment by Hummer12007** [comment]
There you go, @bpinto

**Comment by bpinto** [comment]
Even better @Hummer12007 :)

**Pull request merged**
