### PR TITLE
Respect CFLAGS and LDFLAGS and sort it for easier read

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Comment by Fale** [comment]
1. It seems like 4711 is enough on some systems but not enough on other (that require 4755). Fedora and Debian (https://lists.debian.org/debian-policy/2001/02/msg00106.html) seem to requitre 4755. Also, I think that the difference in security is not present (since this is open source software, and therefore the content of that file can already be read here)

2. Yeah, the LDFLAG ?= is not really needed. Removed it

**Comment by Hummer12007** [comment]
Thanks! Merged after some rebasing.

**Comment by Fale** [comment]
I've noticed that the line 9 change did not make to the repo. Is this a choice or an error?

**Comment by Hummer12007** [comment]
The former. I did some research for major repos as well afterwards, my findings contradicted what you've said.

**Comment by Fale** [comment]
Ok thanks. I'll have to patch it in the SPEC file then, since on Fedora it does not work with 4711. Btw: within few days brightnessctl should hit Fedora repositories :)

**Comment by Hummer12007** [comment]
Thanks a lot (that's weird though, Fedora has had some programs with 4711 acc. to what I've seen).
Though upstream's 4755 is changed to 4711 for a number of packages in Gentoo. So unfortunately no size fits all it seems.

**Pull request closed without merging**
